name: CI - Test Action

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        uses: ./ # Uses an action in the root directory
        with:
          firstname: ${{ secrets.MY_SECRET }}
